# Generated by Django 4.2.18 on 2025-01-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_alter_entregaobsequio_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('obsequio', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('causa', models.CharField(max_length=200)),
                ('preaprobado', models.CharField(max_length=200)),
                ('cuota', models.CharField(max_length=200)),
                ('plazo', models.IntegerField()),
            ],
        ),
    ]
