# Generated by Django 4.2.18 on 2025-01-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_asociados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asociado',
        ),
        migrations.AddField(
            model_name='asesor',
            name='sucursal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
